Repository NilPointer-Software/bdfd-wiki, pull requests merged in 2022-08, with the labels that each got.

#154 Update ...
  src/SUMMARY.md
  src/bdscript/scriptLanguage.md
  src/bdscript/timeout.md
  src/bdscript/untimeout.md
Labels: enhancement

#153 Wiki Updation #3
  CONTRIBUTING.md
  src/SUMMARY.md
  src/bdscript/removeButtons.md
  src/bdscript/scriptLanguage.md
  src/callbacks/onBanAdd.md
  src/callbacks/onBanRemove.md
  src/callbacks/onInteraction.md
  src/callbacks/onJoined.md
  src/callbacks/onLeave.md
  src/callbacks/onMessageDelete.md
  src/foreword.md
  src/guides/bdscript2.md
  src/guides/buttons.md
  src/guides/characterEscaping.md
  src/guides/commandsAnatomy.md
  src/guides/introduction.md
  src/guides/sharecode.md
  src/guides/threads.md
  src/javascript/javascript.md
  src/premium/alwaysReply.md
  src/premium/awaitedReactions.md
  src/premium/customImages.md
  src/premium/customPrefixes.md
  src/premium/ignoreTriggerCase.md
  src/premium/introduction.md
  src/premium/messageContains.md
Labels: enhancement

#157 Update checkUserPerms.md
  src/bdscript/checkUserPerms.md
Labels: bug

#163 Wiki Update & Fix
  src/SUMMARY.md
  src/bdscript/addCmdReactions.md
  src/bdscript/hypesquad.md
  src/bdscript/userServerAvatar.md
  src/callbacks/introduction.md
  src/foreword.md
  src/resources/bdfdCreation.md
Labels: documentation, enhancement
